"""
ML Challenge 2026: Business Entity Resolution
Module: train_data.py

Constructs labeled pairwise machine learning training and validation datasets
from candidate pairs generated by Configuration H blocking:

1. Entity-Level Train/Validation Splitting:
   - 80% Source 1 entities for Training, 20% for Validation (seed=42).
   - Strict entity isolation: zero S1 overlap between splits.
   - Validation retains ALL candidate pairs for unbiased macro F0.5 evaluation.

2. Pairwise Ground-Truth Labeling:
   - Label 1 = True Match (candidate ID in train_ground_truth.tsv for that S1).
   - Label 0 = Non-Match (candidate produced by blocking, but not in ground truth).
   - Strictly uses hard negatives produced by Configuration H (no random Cartesian pairs).

3. Controlled Hard-Negative Sampling & Entity Balancing:
   - 100% of blocking-recalled positive candidate pairs are retained.
   - Negatives prioritized by composite hardness score:
     * High name / transliterated name similarity
     * Multi-rule blocking agreement (e.g. consonant skeleton + postal + address token)
     * Commercial homonyms (exact name, different address)
     * Same postal code or house number
   - Entity balancing: prevents outlier S1 entities from dominating the pairwise loss.
   - Benchmarks multiple negative:positive ratios (1:1, 2:1, 4:1, and unconstrained).

4. High-Performance Feature Matrix Construction:
   - Computes 96 dense float32 features via features.py in chunked streaming batches.
   - Verifies zero NaN and zero infinity values.
   - Saves compressed NPZ archives: dataset/processed/train_data.npz and val_data.npz.

5. Rigorous Ground-Truth Integrity Checks:
   - Every positive pair confirmed in ground truth.
   - Zero negative pairs in ground truth.
   - Zero S1 leakage across splits.
   - All target records confirmed as S2 or S3 (zero S1-S1 pairs).
"""

import os
import sys
import time
import csv
import random
import tracemalloc
from typing import Dict, List, Set, Tuple, Any, Optional
from collections import defaultdict, Counter
import numpy as np

sys.stdout.reconfigure(encoding='utf-8', errors='backslashreplace', line_buffering=True)

# Add src to path
sys.path.insert(0, os.path.dirname(__file__))

from preprocessing import (
    normalize_name,
    compact_string,
    remove_legal_suffix,
    transliterate_name,
    normalize_address,
    extract_postal_code,
    extract_house_number,
    has_indic_characters
)
from blocking import create_config_h_generator
from features import (
    PairwiseFeatureExtractor,
    enrich_record_for_features,
    FEATURE_NAMES,
    NUM_FEATURES,
    safe_normalized_levenshtein,
    jaccard_similarity
)

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, "dataset", "processed")


# ==============================================================================
# 1. Entity-Level Train/Validation Splitting
# ==============================================================================

def split_s1_entities(
    s1_ids: List[str],
    train_ratio: float = 0.80,
    random_seed: int = 42
) -> Tuple[List[str], List[str]]:
    """
    Partitions Source 1 entity IDs into train and validation sets at the S1 entity level.
    Guarantees that all candidate pairs for an S1 entity belong exclusively to one split.
    """
    rng = random.Random(random_seed)
    shuffled = sorted(list(s1_ids))  # Deterministic base ordering
    rng.shuffle(shuffled)

    n_train = int(len(shuffled) * train_ratio)
    train_ids = sorted(shuffled[:n_train])
    val_ids = sorted(shuffled[n_train:])

    # Integrity verification
    assert len(set(train_ids) & set(val_ids)) == 0, "Train/Val S1 overlap detected!"
    assert len(train_ids) + len(val_ids) == len(s1_ids), "S1 entity count mismatch!"

    return train_ids, val_ids


# ==============================================================================
# 2. Hard-Negative Scoring & Prioritization
# ==============================================================================

def compute_negative_hardness(
    s1_rec: Dict[str, Any],
    cand_rec: Dict[str, Any],
    rule_set: Set[str]
) -> float:
    """
    Computes a composite hardness score for a negative candidate pair.
    Higher score indicates a challenging distractor (e.g. homonym, same street/colony,
    multi-rule blocking agreement) that provides high gradient signal for ML training.
    """
    score = 0.0

    # 1. Multi-rule agreement (strongest indicator of challenging distractor)
    score += len(rule_set) * 2.0

    # 2. Specific high-precision rule triggers
    if "blocked_exact_name" in rule_set:
        score += 8.0  # Commercial homonym / franchise (same name, different location)
    if "blocked_compact_name" in rule_set or "blocked_suffix_name" in rule_set:
        score += 6.0
    if "blocked_translit" in rule_set:
        score += 5.0
    if "blocked_consonant_skeleton" in rule_set:
        score += 4.0
    if "blocked_postal" in rule_set:
        score += 4.0
    if "blocked_house" in rule_set:
        score += 3.0
    if "blocked_address_name_combo" in rule_set:
        score += 3.0
    if "blocked_address_token" in rule_set:
        score += 2.0

    # 3. Lexical name similarity
    n1 = s1_rec.get("norm_name", "")
    n2 = cand_rec.get("translit_name", "") if cand_rec.get("has_indic", False) else cand_rec.get("norm_name", "")
    if n1 and n2:
        if n1 == n2:
            score += 5.0
        elif len(n1) >= 3 and len(n2) >= 3 and n1[:3] == n2[:3]:
            score += 2.0

    # 4. Postal code match
    p1 = s1_rec.get("postal_code", "")
    p2 = cand_rec.get("postal_code", "")
    if p1 and p2 and p1.lower() == p2.lower():
        score += 3.0

    # 5. House number match
    h1 = s1_rec.get("house_number", "")
    h2 = cand_rec.get("house_number", "")
    if h1 and h2 and h1.lower() == h2.lower():
        score += 2.0

    return score


# ==============================================================================
# 3. Controlled Negative Sampling with Entity Balancing
# ==============================================================================

def sample_training_pairs_with_ratios(
    train_s1_ids: List[str],
    evidence_map: Dict[str, Dict[str, Set[str]]],
    ground_truth: Dict[str, Set[str]],
    s1_records: Dict[str, Dict[str, Any]],
    cand_records: Dict[str, Dict[str, Any]],
    ratios: List[float] = [1.0, 2.0, 4.0],
    selected_ratio: float = 4.0,
    random_seed: int = 42
) -> Tuple[List[Tuple[str, str, Set[str], int]], Dict[str, Any]]:
    """
    Constructs labeled training pairs across tested negative-to-positive ratios.
    Guarantees:
    - 100% of blocking-recalled positive candidate pairs are preserved.
    - Negatives are sampled using hard-negative prioritization + stochastic diversity.
    - Entity balancing caps per-S1 negatives to prevent outlier entities from dominating.
    """
    rng = random.Random(random_seed)

    # 1. Inspect per-S1 candidate and ground-truth distributions
    pos_counts_per_s1: List[int] = []
    cands_per_s1: List[int] = []
    negs_per_s1: List[int] = []

    s1_positives: Dict[str, List[Tuple[str, Set[str]]]] = defaultdict(list)
    s1_negatives_scored: Dict[str, List[Tuple[str, Set[str], float]]] = defaultdict(list)

    total_avail_pos = 0
    total_avail_neg = 0

    for s1_id in train_s1_ids:
        gt_matches = ground_truth.get(s1_id, set())
        cand_dict = evidence_map.get(s1_id, {})
        cands_per_s1.append(len(cand_dict))

        p_count = 0
        n_count = 0
        for cand_id, rule_set in cand_dict.items():
            if cand_id in gt_matches:
                s1_positives[s1_id].append((cand_id, rule_set))
                p_count += 1
                total_avail_pos += 1
            else:
                s1_rec = s1_records[s1_id]
                cand_rec = cand_records[cand_id]
                h_score = compute_negative_hardness(s1_rec, cand_rec, rule_set)
                s1_negatives_scored[s1_id].append((cand_id, rule_set, h_score))
                n_count += 1
                total_avail_neg += 1

        pos_counts_per_s1.append(p_count)
        negs_per_s1.append(n_count)

    # Ratio comparisons
    ratio_stats: Dict[str, Any] = {}
    for r in ratios:
        r_neg_count = 0
        for s1_id in train_s1_ids:
            p_len = len(s1_positives[s1_id])
            n_len = len(s1_negatives_scored[s1_id])
            target_n = max(2, int(p_len * r)) if p_len > 0 else min(n_len, int(r))
            r_neg_count += min(n_len, target_n)

        ratio_stats[f"ratio_{r:.1f}"] = {
            "positives": total_avail_pos,
            "negatives": r_neg_count,
            "total_pairs": total_avail_pos + r_neg_count,
            "neg_pos_ratio": r_neg_count / total_avail_pos if total_avail_pos > 0 else 0.0,
            "positive_pct": (total_avail_pos / (total_avail_pos + r_neg_count) * 100) if (total_avail_pos + r_neg_count) > 0 else 0.0
        }

    # All negatives baseline
    ratio_stats["unconstrained_all"] = {
        "positives": total_avail_pos,
        "negatives": total_avail_neg,
        "total_pairs": total_avail_pos + total_avail_neg,
        "neg_pos_ratio": total_avail_neg / total_avail_pos if total_avail_pos > 0 else 0.0,
        "positive_pct": (total_avail_pos / (total_avail_pos + total_avail_neg) * 100) if (total_avail_pos + total_avail_neg) > 0 else 0.0
    }

    # 2. Build final training set under selected_ratio (4.0:1) with entity balancing
    selected_training_pairs: List[Tuple[str, str, Set[str], int]] = []
    hard_neg_count = 0
    sampled_negs_per_s1: List[int] = []

    for s1_id in train_s1_ids:
        # A. Include ALL positive candidate pairs
        for cand_id, rule_set in s1_positives[s1_id]:
            selected_training_pairs.append((s1_id, cand_id, rule_set, 1))

        # B. Sample balanced hard negatives
        neg_candidates = s1_negatives_scored[s1_id]
        if not neg_candidates:
            sampled_negs_per_s1.append(0)
            continue

        p_len = len(s1_positives[s1_id])
        # Entity-balanced budget: 4x positives, min 2, max 25 per S1 to cap dominant entities
        if p_len > 0:
            target_n = min(len(neg_candidates), max(2, min(25, int(p_len * selected_ratio))))
        else:
            # Singleton S1 entity (no true match in candidate set)
            target_n = min(len(neg_candidates), 3)

        # Sort negatives by hardness descending
        neg_candidates.sort(key=lambda x: x[2], reverse=True)

        # 80% hardest negatives + 20% randomized negatives for regularization
        n_hard = int(target_n * 0.8)
        n_rand = target_n - n_hard

        chosen_negs: List[Tuple[str, Set[str]]] = []
        for cand_id, rule_set, _ in neg_candidates[:n_hard]:
            chosen_negs.append((cand_id, rule_set))
            hard_neg_count += 1

        remaining_negs = neg_candidates[n_hard:]
        if remaining_negs and n_rand > 0:
            rand_sample = rng.sample(remaining_negs, min(n_rand, len(remaining_negs)))
            for cand_id, rule_set, _ in rand_sample:
                chosen_negs.append((cand_id, rule_set))

        for cand_id, rule_set in chosen_negs:
            selected_training_pairs.append((s1_id, cand_id, rule_set, 0))

        sampled_negs_per_s1.append(len(chosen_negs))

    metadata = {
        "total_avail_pos": total_avail_pos,
        "total_avail_neg": total_avail_neg,
        "ratio_comparisons": ratio_stats,
        "selected_ratio": selected_ratio,
        "final_positives": total_avail_pos,
        "final_negatives": sum(sampled_negs_per_s1),
        "hard_negatives": hard_neg_count,
        "pos_per_s1_stats": {
            "mean": float(np.mean(pos_counts_per_s1)),
            "median": float(np.median(pos_counts_per_s1)),
            "p95": float(np.percentile(pos_counts_per_s1, 95)),
            "max": int(np.max(pos_counts_per_s1)),
            "zero_pos_s1_count": int(sum(1 for c in pos_counts_per_s1 if c == 0))
        },
        "neg_per_s1_stats": {
            "mean": float(np.mean(negs_per_s1)),
            "median": float(np.median(negs_per_s1)),
            "p95": float(np.percentile(negs_per_s1, 95)),
            "max": int(np.max(negs_per_s1)),
        },
        "sampled_neg_per_s1_stats": {
            "mean": float(np.mean(sampled_negs_per_s1)),
            "median": float(np.median(sampled_negs_per_s1)),
            "p95": float(np.percentile(sampled_negs_per_s1, 95)),
            "max": int(np.max(sampled_negs_per_s1)),
        },
        "cands_per_s1_stats": {
            "mean": float(np.mean(cands_per_s1)),
            "median": float(np.median(cands_per_s1)),
            "p95": float(np.percentile(cands_per_s1, 95)),
            "max": int(np.max(cands_per_s1)),
        }
    }

    return selected_training_pairs, metadata


# ==============================================================================
# 4. End-to-End Dataset Construction & Serialization Pipeline
# ==============================================================================

def prepare_lightweight_record(eid: str, name: str, addr: str, country: str) -> Dict[str, Any]:
    """Prepares lightweight preprocessed record sufficient for blocking and negative scoring."""
    norm_n = normalize_name(name)
    has_ind = has_indic_characters(name)
    return {
        "entity_id": eid,
        "name": name,
        "address": addr,
        "country": country,
        "norm_name": norm_n,
        "compact_name": compact_string(norm_n),
        "nosuff_name": remove_legal_suffix(norm_n),
        "translit_name": transliterate_name(name) if has_ind else norm_n,
        "has_indic": has_ind,
        "postal_code": extract_postal_code(addr),
        "house_number": extract_house_number(addr),
        "norm_address": normalize_address(addr),
    }


def build_training_and_validation_datasets(cohort_size: int = 10000, random_seed: int = 42) -> Dict[str, Any]:
    """
    Main orchestration routine building labeled train and validation datasets:
    1. Ingests stratified S1 cohort and target records.
    2. Runs Configuration H blocking with rule evidence tracking.
    3. Partitions S1 entities (80% train / 20% val).
    4. Labels pairs and applies entity-balanced hard-negative sampling to train split.
    5. Retains all candidate pairs for validation split.
    6. Extracts 96-dimensional float32 feature matrices via features.py.
    7. Runs comprehensive ground-truth verification assertions.
    8. Serializes datasets to dataset/processed/train_data.npz and val_data.npz.
    """
    print("=" * 80, flush=True)
    print("LABELED PAIRWISE TRAINING DATASET CONSTRUCTION", flush=True)
    print("=" * 80, flush=True)

    t_start = time.time()
    tracemalloc.start()
    os.makedirs(PROCESSED_DATA_DIR, exist_ok=True)

    # 1. Ingest S1 Cohort (Stratified US & India)
    us_target = int(cohort_size * 0.60)
    ind_target = int(cohort_size * 0.40)
    print(f"\n[1/6] Ingesting Stratified S1 Cohort ({cohort_size:,} records: {us_target:,} US, {ind_target:,} India)...", flush=True)

    s1_records: Dict[str, Dict[str, Any]] = {}
    us_count, ind_count = 0, 0
    s1_path = os.path.join(BASE_DIR, "dataset", "train", "train_source1.tsv")

    with open(s1_path, "r", encoding="utf-8") as f:
        r = csv.reader(f, delimiter="\t")
        next(r)
        for row in r:
            eid, name, addr, country = row[0], row[1], row[2], row[3]
            if country == "US" and us_count < us_target:
                s1_records[eid] = prepare_lightweight_record(eid, name, addr, country)
                us_count += 1
            elif country == "India" and ind_count < ind_target:
                s1_records[eid] = prepare_lightweight_record(eid, name, addr, country)
                ind_count += 1
            if us_count >= us_target and ind_count >= ind_target:
                break

    print(f"  S1 Cohort loaded: {len(s1_records):,} records ({us_count:,} US, {ind_count:,} India)", flush=True)

    # 2. Ingest Ground Truth Labels
    print("\n[2/6] Loading Ground Truth Labels...", flush=True)
    ground_truth: Dict[str, Set[str]] = {}
    needed_targets = set()
    gt_path = os.path.join(BASE_DIR, "dataset", "train", "train_ground_truth.tsv")

    with open(gt_path, "r", encoding="utf-8") as f:
        r = csv.reader(f, delimiter="\t")
        next(r)
        for row in r:
            s1_id = row[0]
            if s1_id in s1_records:
                matches = set(x.strip() for x in row[1].split(",") if x.strip())
                ground_truth[s1_id] = matches
                needed_targets.update(matches)

    total_gt_links = sum(len(m) for m in ground_truth.values())
    print(f"  Total true links in cohort: {total_gt_links:,}", flush=True)

    # 3. Ingest Target Pool (All true matches + 400k distractors)
    print("\n[3/6] Ingesting Target Pool (True matches + 400,000 distractors)...", flush=True)
    target_records: Dict[str, Dict[str, Any]] = {}
    needed_s2 = {eid for eid in needed_targets if eid.startswith("S2-")}
    needed_s3 = {eid for eid in needed_targets if eid.startswith("S3-")}

    for fname, needed_set, distractor_limit in [
        ("train_source2.tsv", needed_s2, 200000),
        ("train_source3.tsv", needed_s3, 200000)
    ]:
        fpath = os.path.join(BASE_DIR, "dataset", "train", fname)
        with open(fpath, "r", encoding="utf-8") as f:
            r = csv.reader(f, delimiter="\t")
            next(r)
            d_count = 0
            for row in r:
                eid, name, addr, country = row[0], row[1], row[2], row[3]
                if eid in needed_set or d_count < distractor_limit:
                    target_records[eid] = prepare_lightweight_record(eid, name, addr, country)
                    if eid not in needed_set:
                        d_count += 1

    print(f"  Target pool size: {len(target_records):,} records", flush=True)

    # 4. Generate Candidates under Configuration H with Evidence Tracking
    print("\n[4/6] Executing Configuration H Candidate Generation with Rule Provenance...", flush=True)
    blocker = create_config_h_generator(ngram_top_k=10, ngram_min_sim=0.25)
    t_block_start = time.time()
    blocker.fit_target_records(list(target_records.values()))
    evidence_map = blocker.generate_candidates_with_evidence(list(s1_records.values()))
    t_block_end = time.time()
    print(f"  Candidate generation completed in {t_block_end - t_block_start:.2f}s", flush=True)

    # 5. Entity-Level Train/Validation Splitting (80/20)
    print("\n[5/6] Splitting S1 Entities into Train (80%) and Validation (20%) [seed=42]...", flush=True)
    all_s1_ids = list(s1_records.keys())
    train_s1_ids, val_s1_ids = split_s1_entities(all_s1_ids, train_ratio=0.80, random_seed=random_seed)

    print(f"  Training S1 entities   : {len(train_s1_ids):,} (80.0%)", flush=True)
    print(f"  Validation S1 entities : {len(val_s1_ids):,} (20.0%)", flush=True)

    # Measure blocking recall on each split
    train_gt_links = sum(len(ground_truth.get(s1, set())) for s1 in train_s1_ids)
    val_gt_links = sum(len(ground_truth.get(s1, set())) for s1 in val_s1_ids)

    train_recalled = sum(
        1 for s1 in train_s1_ids
        for m in ground_truth.get(s1, set())
        if m in evidence_map.get(s1, {})
    )
    val_recalled = sum(
        1 for s1 in val_s1_ids
        for m in ground_truth.get(s1, set())
        if m in evidence_map.get(s1, {})
    )

    print(f"  Train True Links: {train_gt_links:,} | Recalled: {train_recalled:,} ({train_recalled/train_gt_links*100:.2f}%) | Missed: {train_gt_links - train_recalled:,}", flush=True)
    print(f"  Val True Links  : {val_gt_links:,} | Recalled: {val_recalled:,} ({val_recalled/val_gt_links*100:.2f}%) | Missed: {val_gt_links - val_recalled:,}", flush=True)

    # Build Training Pairs with Negative Sampling
    train_pairs, train_meta = sample_training_pairs_with_ratios(
        train_s1_ids=train_s1_ids,
        evidence_map=evidence_map,
        ground_truth=ground_truth,
        s1_records=s1_records,
        cand_records=target_records,
        ratios=[1.0, 2.0, 4.0],
        selected_ratio=4.0,
        random_seed=random_seed
    )

    # Build Validation Pairs (ALL candidate pairs retained)
    val_pairs: List[Tuple[str, str, Set[str], int]] = []
    val_pos_count = 0
    val_neg_count = 0

    for s1_id in val_s1_ids:
        gt_matches = ground_truth.get(s1_id, set())
        for cand_id, rule_set in evidence_map.get(s1_id, {}).items():
            if cand_id in target_records:
                is_match = 1 if cand_id in gt_matches else 0
                val_pairs.append((s1_id, cand_id, rule_set, is_match))
                if is_match == 1:
                    val_pos_count += 1
                else:
                    val_neg_count += 1

    print(f"\n  Final Selected Training Pairs   : {len(train_pairs):,} (Pos: {train_meta['final_positives']:,}, Neg: {train_meta['final_negatives']:,})", flush=True)
    print(f"  Validation Candidate Pairs (100%): {len(val_pairs):,} (Pos: {val_pos_count:,}, Neg: {val_neg_count:,})", flush=True)

    # 6. Extract Feature Matrices
    print("\n[6/6] Extracting 96-Dimensional Feature Matrices (Chunked Streaming)...", flush=True)
    
    # Selective enrichment: only enrich entities appearing in train or val candidate pairs
    needed_s1_ids = set(train_s1_ids) | set(val_s1_ids)
    print(f"  Enriching {len(needed_s1_ids):,} S1 entities for feature extraction...", flush=True)
    t_enr0 = time.time()
    enriched_s1 = {eid: enrich_record_for_features(s1_records[eid]) for eid in needed_s1_ids}
    
    needed_target_ids = {p[1] for p in train_pairs} | {p[1] for p in val_pairs}
    print(f"  Enriching {len(needed_target_ids):,} candidate target records for feature extraction...", flush=True)
    enriched_targets = {eid: enrich_record_for_features(target_records[eid]) for eid in needed_target_ids}
    t_enr1 = time.time()
    print(f"  Enrichment completed in {t_enr1 - t_enr0:.2f}s", flush=True)

    extractor = PairwiseFeatureExtractor()

    t_feat_start = time.time()
    # Training Matrix
    train_tuples = [(p[0], p[1], p[2]) for p in train_pairs]
    y_train = np.array([p[3] for p in train_pairs], dtype=np.int32)
    X_train = extractor.extract_batch_vectors(enriched_s1, enriched_targets, train_tuples, chunk_size=10000)

    # Validation Matrix
    val_tuples = [(p[0], p[1], p[2]) for p in val_pairs]
    y_val = np.array([p[3] for p in val_pairs], dtype=np.int32)
    X_val = extractor.extract_batch_vectors(enriched_s1, enriched_targets, val_tuples, chunk_size=10000)
    t_feat_end = time.time()

    print(f"  Feature extraction finished in {t_feat_end - t_feat_start:.2f}s ({len(train_pairs) + len(val_pairs):,} pairs)", flush=True)

    # 7. Rigorous Ground-Truth Integrity Checks
    print("\n--- Running Mandatory Ground-Truth Integrity Checks ---", flush=True)

    # Check 1: Every positive training pair exists in ground truth
    train_gt_check_pos = all(p[1] in ground_truth.get(p[0], set()) for p in train_pairs if p[3] == 1)
    assert train_gt_check_pos, "Check 1 Failed: False positive labeled as positive in train!"
    print("  [Pass] Check 1: 100% of positive training pairs exist in ground truth.", flush=True)

    # Check 2: No negative training pair exists in ground truth
    train_gt_check_neg = all(p[1] not in ground_truth.get(p[0], set()) for p in train_pairs if p[3] == 0)
    assert train_gt_check_neg, "Check 2 Failed: Ground-truth true match labeled as negative in train!"
    print("  [Pass] Check 2: Zero negative training pairs exist in ground truth.", flush=True)

    # Check 3: No S1 entity occurs in both train and validation
    train_s1_set = set(p[0] for p in train_pairs)
    val_s1_set = set(p[0] for p in val_pairs)
    assert len(train_s1_set & val_s1_set) == 0, "Check 3 Failed: S1 entity overlap across splits!"
    print("  [Pass] Check 3: Zero S1 entity overlap between train and validation splits.", flush=True)

    # Check 4: Every target pair is S1 -> S2 or S1 -> S3
    all_targets_valid = all(
        p[1].startswith("S2-") or p[1].startswith("S3-")
        for p in train_pairs + val_pairs
    )
    assert all_targets_valid, "Check 4 Failed: Invalid candidate entity source prefix!"
    print("  [Pass] Check 4: 100% of target candidates are Source 2 or Source 3 records.", flush=True)

    # Check 5: No S1 -> S1 pair exists
    no_self_pairs = all(
        not p[1].startswith("S1-")
        for p in train_pairs + val_pairs
    )
    assert no_self_pairs, "Check 5 Failed: Detected S1 -> S1 self-pair!"
    print("  [Pass] Check 5: Zero S1 -> S1 candidate pairs exist.", flush=True)

    # Check 6: Matrix finiteness
    assert np.isnan(X_train).sum() == 0, "NaN detected in X_train!"
    assert np.isinf(X_train).sum() == 0, "Infinity detected in X_train!"
    assert np.isnan(X_val).sum() == 0, "NaN detected in X_val!"
    assert np.isinf(X_val).sum() == 0, "Infinity detected in X_val!"
    print("  [Pass] Check 6: Zero NaN and zero infinity values across feature matrices.", flush=True)

    # 8. Disk Serialization (Compressed NPZ)
    print("\n--- Serializing Datasets to Disk ---", flush=True)
    train_file = os.path.join(PROCESSED_DATA_DIR, "train_data.npz")
    val_file = os.path.join(PROCESSED_DATA_DIR, "val_data.npz")

    s1_train_arr = np.array([p[0] for p in train_pairs], dtype=object)
    cand_train_arr = np.array([p[1] for p in train_pairs], dtype=object)
    np.savez_compressed(
        train_file,
        X=X_train,
        y=y_train,
        s1_ids=s1_train_arr,
        cand_ids=cand_train_arr,
        feature_names=np.array(FEATURE_NAMES)
    )

    s1_val_arr = np.array([p[0] for p in val_pairs], dtype=object)
    cand_val_arr = np.array([p[1] for p in val_pairs], dtype=object)
    np.savez_compressed(
        val_file,
        X=X_val,
        y=y_val,
        s1_ids=s1_val_arr,
        cand_ids=cand_val_arr,
        feature_names=np.array(FEATURE_NAMES)
    )

    train_disk_mb = os.path.getsize(train_file) / (1024 * 1024)
    val_disk_mb = os.path.getsize(val_file) / (1024 * 1024)
    total_disk_mb = train_disk_mb + val_disk_mb

    current_mem, peak_mem = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    total_runtime = time.time() - t_start

    print(f"  Saved Train Dataset : {train_file} ({train_disk_mb:.2f} MB)", flush=True)
    print(f"  Saved Val Dataset   : {val_file} ({val_disk_mb:.2f} MB)", flush=True)
    print(f"  Total Disk Usage    : {total_disk_mb:.2f} MB", flush=True)
    print(f"  Peak RAM Overhead   : {peak_mem / (1024 * 1024):.2f} MB", flush=True)
    print(f"  Total Pipeline Time : {total_runtime:.2f} seconds", flush=True)

    results = {
        "train_s1_count": len(train_s1_ids),
        "val_s1_count": len(val_s1_ids),
        "total_cands_avail": train_meta["total_avail_pos"] + train_meta["total_avail_neg"] + len(val_pairs),
        "train_avail_pos": train_meta["total_avail_pos"],
        "train_avail_neg": train_meta["total_avail_neg"],
        "train_gt_links": train_gt_links,
        "val_gt_links": val_gt_links,
        "train_recalled_pos": train_recalled,
        "val_recalled_pos": val_recalled,
        "train_lost_pos": train_gt_links - train_recalled,
        "val_lost_pos": val_gt_links - val_recalled,
        "ratio_comparisons": train_meta["ratio_comparisons"],
        "final_ratio": train_meta["selected_ratio"],
        "train_final_pos": train_meta["final_positives"],
        "train_final_neg": train_meta["final_negatives"],
        "train_hard_neg": train_meta["hard_negatives"],
        "val_pairs_count": len(val_pairs),
        "val_pos_count": val_pos_count,
        "val_neg_count": val_neg_count,
        "X_train_shape": X_train.shape,
        "X_val_shape": X_val.shape,
        "train_matrix_mb": X_train.nbytes / (1024 * 1024),
        "val_matrix_mb": X_val.nbytes / (1024 * 1024),
        "train_disk_mb": train_disk_mb,
        "val_disk_mb": val_disk_mb,
        "total_disk_mb": total_disk_mb,
        "peak_ram_mb": peak_mem / (1024 * 1024),
        "total_runtime_s": total_runtime,
        "pos_per_s1_stats": train_meta["pos_per_s1_stats"],
        "neg_per_s1_stats": train_meta["neg_per_s1_stats"],
        "sampled_neg_per_s1_stats": train_meta["sampled_neg_per_s1_stats"],
        "cands_per_s1_stats": train_meta["cands_per_s1_stats"]
    }

    return results


if __name__ == "__main__":
    build_training_and_validation_datasets(cohort_size=10000, random_seed=42)
